services:
  typedb:
    container_name: typedb
    hostname: typedb
    cap_add:
      - SYS_NICE
    restart: "no"
    build:
      context: mysql
      dockerfile: mysql8.0_ubuntu24_Dockerfile
    working_dir: /mysql
    env_file:
      - ./.env
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql:/mysql
    # command: ["mysqld"]

  exp_stan:
    container_name: exp_stan
    hostname: exp_stan
    depends_on:
      - typedb
    build:
      context: express_standard
      dockerfile: ../Dockerfile.ubuntu
    working_dir: /var/app/current
    env_file:
      - ./.env
    ports:
      - "${EXP_STAN_HOST_PORT}:${EXP_STAN_CONTAINER_PORT}"
      - "${EXP_STAN_HOST_DEBUG_PORT}:${EXP_STAN_CONTAINER_DEBUG_PORT}"
    stdin_open: true
    tty: true
    volumes:
      - "./express_standard:/var/app/current"
    command: sh -c "bash /var/app/current/docker_init.sh"

#  exp_type:
#    container_name: exp_type
#    hostname: exp_type
#    depends_on:
#      - typedb
#    build:
#      context: express_typescript
#      dockerfile: ../Dockerfile.ubuntu
#    working_dir: /var/app/current
#    env_file:
#      - ./.env
#    ports:
#      - "${EXP_TYPE_HOST_PORT}:${EXP_TYPE_CONTAINER_PORT}"
#      - "${EXP_TYPE_HOST_DEBUG_PORT}:${EXP_TYPE_CONTAINER_DEBUG_PORT}"
#    stdin_open: true
#    tty: true
#    volumes:
#      - "./express_typescript:/var/app/current"
#    command: sh -c "bash /var/app/current/docker_init.sh"
#
#  fas_type:
#    container_name: fas_type
#    hostname: fas_type
#    depends_on:
#      - typedb
#    build:
#      context: fastify_typescript
#      dockerfile: ../Dockerfile.ubuntu
#    working_dir: /var/app/current
#    env_file:
#      - ./.env
#    ports:
#      - "${FAS_TYPE_HOST_PORT}:${FAS_TYPE_CONTAINER_PORT}"
#      - "${FAS_TYPE_HOST_DEBUG_PORT}:${FAS_TYPE_CONTAINER_DEBUG_PORT}"
#    stdin_open: true
#    tty: true
#    volumes:
#      - "./fastify_typescript:/var/app/current"
#    command: sh -c "bash /var/app/current/docker_init.sh"